version: "3"

services:
  app:
    build:
      context: .
    ports:
     - "8000:8000"
    volumes:
     - ./app:/app
    command: >
      # Run on django development server in all ip addresses in docker container
      sh -c "python manage.py runsever 0.0.0.0:8000"
